//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.16 at 09:21:05 PM CET 
//


package no.rtv.namespacetss;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Dette er en type som beskriver elementene til samhandler adresse data
 * 
 * <p>Java class for adresseSamhType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adresseSamhType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.rtv.no/NamespaceTSS}adresseGrpType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="antAdrRegion" type="{http://www.rtv.no/NamespaceTSS}Tantallforekomster"/&gt;
 *         &lt;element name="adrRegionInfo" type="{http://www.rtv.no/NamespaceTSS}adrRegionInfoType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adresseSamhType", propOrder = {
    "antAdrRegion",
    "adrRegionInfo"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:05+01:00", comments = "JAXB RI v2.3.0")
public class AdresseSamhType
    extends AdresseGrpType
{

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:05+01:00", comments = "JAXB RI v2.3.0")
    protected String antAdrRegion;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:05+01:00", comments = "JAXB RI v2.3.0")
    protected AdrRegionInfoType adrRegionInfo;

    /**
     * Gets the value of the antAdrRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:05+01:00", comments = "JAXB RI v2.3.0")
    public String getAntAdrRegion() {
        return antAdrRegion;
    }

    /**
     * Sets the value of the antAdrRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:05+01:00", comments = "JAXB RI v2.3.0")
    public void setAntAdrRegion(String value) {
        this.antAdrRegion = value;
    }

    /**
     * Gets the value of the adrRegionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdrRegionInfoType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:05+01:00", comments = "JAXB RI v2.3.0")
    public AdrRegionInfoType getAdrRegionInfo() {
        return adrRegionInfo;
    }

    /**
     * Sets the value of the adrRegionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdrRegionInfoType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:05+01:00", comments = "JAXB RI v2.3.0")
    public void setAdrRegionInfo(AdrRegionInfoType value) {
        this.adrRegionInfo = value;
    }

}
