//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dette er en type som beskriver elementene til samhandler autorisasjonrettigheter
 * 
 * <p>Java class for autorRettighetType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="autorRettighetType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="kodeAutorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="kodeAutRett" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="beskrAutRett" type="{http://www.rtv.no/NamespaceTSS}Tbeskr40v"/>
 *         <element name="datoAutRettFom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="datoAutRettTom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="datoVedtakGitt" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="datoVedtakMistet" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="gyldigAutRett" type="{http://www.rtv.no/NamespaceTSS}Tgyldig"/>
 *         <element name="kilde" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="brukerId" type="{http://www.rtv.no/NamespaceTSS}Tbrukerid"/>
 *         <element name="tidReg" type="{http://www.rtv.no/NamespaceTSS}Ttidreg"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "autorRettighetType", propOrder = {
    "kodeAutorType",
    "kodeAutRett",
    "beskrAutRett",
    "datoAutRettFom",
    "datoAutRettTom",
    "datoVedtakGitt",
    "datoVedtakMistet",
    "gyldigAutRett",
    "kilde",
    "brukerId",
    "tidReg"
})
public class AutorRettighetType {

    @XmlElement(required = true)
    protected String kodeAutorType;
    @XmlElement(required = true)
    protected String kodeAutRett;
    @XmlElement(required = true)
    protected String beskrAutRett;
    @XmlElement(required = true)
    protected String datoAutRettFom;
    @XmlElement(required = true)
    protected String datoAutRettTom;
    @XmlElement(required = true)
    protected String datoVedtakGitt;
    @XmlElement(required = true)
    protected String datoVedtakMistet;
    @XmlElement(required = true)
    protected String gyldigAutRett;
    @XmlElement(required = true)
    protected String kilde;
    @XmlElement(required = true)
    protected String brukerId;
    @XmlElement(required = true)
    protected String tidReg;

    /**
     * Gets the value of the kodeAutorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeAutorType() {
        return kodeAutorType;
    }

    /**
     * Sets the value of the kodeAutorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeAutorType(String value) {
        this.kodeAutorType = value;
    }

    /**
     * Gets the value of the kodeAutRett property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeAutRett() {
        return kodeAutRett;
    }

    /**
     * Sets the value of the kodeAutRett property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeAutRett(String value) {
        this.kodeAutRett = value;
    }

    /**
     * Gets the value of the beskrAutRett property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeskrAutRett() {
        return beskrAutRett;
    }

    /**
     * Sets the value of the beskrAutRett property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeskrAutRett(String value) {
        this.beskrAutRett = value;
    }

    /**
     * Gets the value of the datoAutRettFom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoAutRettFom() {
        return datoAutRettFom;
    }

    /**
     * Sets the value of the datoAutRettFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoAutRettFom(String value) {
        this.datoAutRettFom = value;
    }

    /**
     * Gets the value of the datoAutRettTom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoAutRettTom() {
        return datoAutRettTom;
    }

    /**
     * Sets the value of the datoAutRettTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoAutRettTom(String value) {
        this.datoAutRettTom = value;
    }

    /**
     * Gets the value of the datoVedtakGitt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoVedtakGitt() {
        return datoVedtakGitt;
    }

    /**
     * Sets the value of the datoVedtakGitt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoVedtakGitt(String value) {
        this.datoVedtakGitt = value;
    }

    /**
     * Gets the value of the datoVedtakMistet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoVedtakMistet() {
        return datoVedtakMistet;
    }

    /**
     * Sets the value of the datoVedtakMistet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoVedtakMistet(String value) {
        this.datoVedtakMistet = value;
    }

    /**
     * Gets the value of the gyldigAutRett property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGyldigAutRett() {
        return gyldigAutRett;
    }

    /**
     * Sets the value of the gyldigAutRett property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGyldigAutRett(String value) {
        this.gyldigAutRett = value;
    }

    /**
     * Gets the value of the kilde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKilde() {
        return kilde;
    }

    /**
     * Sets the value of the kilde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKilde(String value) {
        this.kilde = value;
    }

    /**
     * Gets the value of the brukerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrukerId() {
        return brukerId;
    }

    /**
     * Sets the value of the brukerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrukerId(String value) {
        this.brukerId = value;
    }

    /**
     * Gets the value of the tidReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTidReg() {
        return tidReg;
    }

    /**
     * Sets the value of the tidReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTidReg(String value) {
        this.tidReg = value;
    }

}
