//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dette er en type som beskriver elementene til autorisasjoner
 * 
 * <p>Java class for autorisasjonType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="autorisasjonType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="kodeAutorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="beskrAutorType" type="{http://www.rtv.no/NamespaceTSS}Tbeskr40v"/>
 *         <element name="datoAutorFom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="datoAutorTom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="autorId">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="0"/>
 *               <maxLength value="15"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="gyldigAutor" type="{http://www.rtv.no/NamespaceTSS}Tgyldig"/>
 *         <element name="kilde">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="brukerId" type="{http://www.rtv.no/NamespaceTSS}Tbrukerid"/>
 *         <element name="tidReg" type="{http://www.rtv.no/NamespaceTSS}Ttidreg"/>
 *         <element name="antAutorRett" type="{http://www.rtv.no/NamespaceTSS}Tantallforekomster" minOccurs="0"/>
 *         <element name="autorRettInfo" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence minOccurs="0">
 *                   <element name="autorRettighet" type="{http://www.rtv.no/NamespaceTSS}autorRettighetType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "autorisasjonType", propOrder = {
    "kodeAutorType",
    "beskrAutorType",
    "datoAutorFom",
    "datoAutorTom",
    "autorId",
    "gyldigAutor",
    "kilde",
    "brukerId",
    "tidReg",
    "antAutorRett",
    "autorRettInfo"
})
public class AutorisasjonType {

    @XmlElement(required = true)
    protected String kodeAutorType;
    @XmlElement(required = true)
    protected String beskrAutorType;
    @XmlElement(required = true)
    protected String datoAutorFom;
    @XmlElement(required = true)
    protected String datoAutorTom;
    @XmlElement(required = true)
    protected String autorId;
    @XmlElement(required = true)
    protected String gyldigAutor;
    @XmlElement(required = true)
    protected String kilde;
    @XmlElement(required = true)
    protected String brukerId;
    @XmlElement(required = true)
    protected String tidReg;
    protected String antAutorRett;
    protected AutorisasjonType.AutorRettInfo autorRettInfo;

    /**
     * Gets the value of the kodeAutorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeAutorType() {
        return kodeAutorType;
    }

    /**
     * Sets the value of the kodeAutorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeAutorType(String value) {
        this.kodeAutorType = value;
    }

    /**
     * Gets the value of the beskrAutorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeskrAutorType() {
        return beskrAutorType;
    }

    /**
     * Sets the value of the beskrAutorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeskrAutorType(String value) {
        this.beskrAutorType = value;
    }

    /**
     * Gets the value of the datoAutorFom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoAutorFom() {
        return datoAutorFom;
    }

    /**
     * Sets the value of the datoAutorFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoAutorFom(String value) {
        this.datoAutorFom = value;
    }

    /**
     * Gets the value of the datoAutorTom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoAutorTom() {
        return datoAutorTom;
    }

    /**
     * Sets the value of the datoAutorTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoAutorTom(String value) {
        this.datoAutorTom = value;
    }

    /**
     * Gets the value of the autorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutorId() {
        return autorId;
    }

    /**
     * Sets the value of the autorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutorId(String value) {
        this.autorId = value;
    }

    /**
     * Gets the value of the gyldigAutor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGyldigAutor() {
        return gyldigAutor;
    }

    /**
     * Sets the value of the gyldigAutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGyldigAutor(String value) {
        this.gyldigAutor = value;
    }

    /**
     * Gets the value of the kilde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKilde() {
        return kilde;
    }

    /**
     * Sets the value of the kilde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKilde(String value) {
        this.kilde = value;
    }

    /**
     * Gets the value of the brukerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrukerId() {
        return brukerId;
    }

    /**
     * Sets the value of the brukerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrukerId(String value) {
        this.brukerId = value;
    }

    /**
     * Gets the value of the tidReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTidReg() {
        return tidReg;
    }

    /**
     * Sets the value of the tidReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTidReg(String value) {
        this.tidReg = value;
    }

    /**
     * Gets the value of the antAutorRett property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntAutorRett() {
        return antAutorRett;
    }

    /**
     * Sets the value of the antAutorRett property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntAutorRett(String value) {
        this.antAutorRett = value;
    }

    /**
     * Gets the value of the autorRettInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AutorisasjonType.AutorRettInfo }
     *     
     */
    public AutorisasjonType.AutorRettInfo getAutorRettInfo() {
        return autorRettInfo;
    }

    /**
     * Sets the value of the autorRettInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutorisasjonType.AutorRettInfo }
     *     
     */
    public void setAutorRettInfo(AutorisasjonType.AutorRettInfo value) {
        this.autorRettInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence minOccurs="0">
     *         <element name="autorRettighet" type="{http://www.rtv.no/NamespaceTSS}autorRettighetType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "autorRettighet"
    })
    public static class AutorRettInfo {

        protected List<AutorRettighetType> autorRettighet;

        /**
         * Gets the value of the autorRettighet property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the autorRettighet property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getAutorRettighet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AutorRettighetType }
         * </p>
         * 
         * 
         * @return
         *     The value of the autorRettighet property.
         */
        public List<AutorRettighetType> getAutorRettighet() {
            if (autorRettighet == null) {
                autorRettighet = new ArrayList<>();
            }
            return this.autorRettighet;
        }

    }

}
