//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dette er en type som beskriver elementene til samhandler kontakter
 * 
 * <p>Java class for kontaktType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="kontaktType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="avdNr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="kodeKontaktType">
 *           <simpleType>
 *             <restriction base="{http://www.rtv.no/NamespaceTSS}Tkodekontakttype">
 *               <whiteSpace value="collapse"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="beskrKontaktType" type="{http://www.rtv.no/NamespaceTSS}Tbeskr40v"/>
 *         <element name="kontakt">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="80"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="datoKontaktFom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="datoKontaktTom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="gyldigKontakt" type="{http://www.rtv.no/NamespaceTSS}Tgyldig"/>
 *         <element name="kilde">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="brukerId" type="{http://www.rtv.no/NamespaceTSS}Tbrukerid"/>
 *         <element name="tidReg" type="{http://www.rtv.no/NamespaceTSS}Ttidreg"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kontaktType", propOrder = {
    "avdNr",
    "kodeKontaktType",
    "beskrKontaktType",
    "kontakt",
    "datoKontaktFom",
    "datoKontaktTom",
    "gyldigKontakt",
    "kilde",
    "brukerId",
    "tidReg"
})
public class KontaktType {

    @XmlElement(required = true)
    protected String avdNr;
    @XmlElement(required = true)
    protected String kodeKontaktType;
    @XmlElement(required = true)
    protected String beskrKontaktType;
    @XmlElement(required = true)
    protected String kontakt;
    @XmlElement(required = true)
    protected String datoKontaktFom;
    @XmlElement(required = true)
    protected String datoKontaktTom;
    @XmlElement(required = true)
    protected String gyldigKontakt;
    @XmlElement(required = true)
    protected String kilde;
    @XmlElement(required = true)
    protected String brukerId;
    @XmlElement(required = true)
    protected String tidReg;

    /**
     * Gets the value of the avdNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvdNr() {
        return avdNr;
    }

    /**
     * Sets the value of the avdNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvdNr(String value) {
        this.avdNr = value;
    }

    /**
     * Gets the value of the kodeKontaktType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeKontaktType() {
        return kodeKontaktType;
    }

    /**
     * Sets the value of the kodeKontaktType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeKontaktType(String value) {
        this.kodeKontaktType = value;
    }

    /**
     * Gets the value of the beskrKontaktType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeskrKontaktType() {
        return beskrKontaktType;
    }

    /**
     * Sets the value of the beskrKontaktType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeskrKontaktType(String value) {
        this.beskrKontaktType = value;
    }

    /**
     * Gets the value of the kontakt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKontakt() {
        return kontakt;
    }

    /**
     * Sets the value of the kontakt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKontakt(String value) {
        this.kontakt = value;
    }

    /**
     * Gets the value of the datoKontaktFom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoKontaktFom() {
        return datoKontaktFom;
    }

    /**
     * Sets the value of the datoKontaktFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoKontaktFom(String value) {
        this.datoKontaktFom = value;
    }

    /**
     * Gets the value of the datoKontaktTom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoKontaktTom() {
        return datoKontaktTom;
    }

    /**
     * Sets the value of the datoKontaktTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoKontaktTom(String value) {
        this.datoKontaktTom = value;
    }

    /**
     * Gets the value of the gyldigKontakt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGyldigKontakt() {
        return gyldigKontakt;
    }

    /**
     * Sets the value of the gyldigKontakt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGyldigKontakt(String value) {
        this.gyldigKontakt = value;
    }

    /**
     * Gets the value of the kilde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKilde() {
        return kilde;
    }

    /**
     * Sets the value of the kilde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKilde(String value) {
        this.kilde = value;
    }

    /**
     * Gets the value of the brukerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrukerId() {
        return brukerId;
    }

    /**
     * Sets the value of the brukerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrukerId(String value) {
        this.brukerId = value;
    }

    /**
     * Gets the value of the tidReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTidReg() {
        return tidReg;
    }

    /**
     * Sets the value of the tidReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTidReg(String value) {
        this.tidReg = value;
    }

}
