//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.16 at 09:21:05 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.rtv.no/NamespaceTSS", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package no.rtv.namespacetss;
