//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 03:51:48 PM CET 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Inneholder elementene som skal være med i en 180-rekord ved oppdatering
 * 
 * <p>Java class for samhAjour180Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="samhAjour180Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idOff" type="{http://www.rtv.no/NamespaceTSS}Tidoff"/&gt;
 *         &lt;element name="kodeIdType" type="{http://www.rtv.no/NamespaceTSS}TkodeIdenttype"/&gt;
 *         &lt;element name="kodeSamhType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kodeRelasjonRolle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="datoRelFom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/&gt;
 *         &lt;element name="datoRelTom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/&gt;
 *         &lt;element name="gyldigRelasjon" type="{http://www.rtv.no/NamespaceTSS}Tgyldig"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samhAjour180Type", propOrder = {
    "idOff",
    "kodeIdType",
    "kodeSamhType",
    "kodeRelasjonRolle",
    "datoRelFom",
    "datoRelTom",
    "gyldigRelasjon"
})
public class SamhAjour180Type {

    @XmlElement(required = true)
    protected String idOff;
    @XmlElement(required = true)
    protected String kodeIdType;
    @XmlElement(required = true)
    protected String kodeSamhType;
    @XmlElement(required = true)
    protected String kodeRelasjonRolle;
    @XmlElement(required = true)
    protected String datoRelFom;
    @XmlElement(required = true)
    protected String datoRelTom;
    @XmlElement(required = true)
    protected String gyldigRelasjon;

    /**
     * Gets the value of the idOff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdOff() {
        return idOff;
    }

    /**
     * Sets the value of the idOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdOff(String value) {
        this.idOff = value;
    }

    /**
     * Gets the value of the kodeIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeIdType() {
        return kodeIdType;
    }

    /**
     * Sets the value of the kodeIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeIdType(String value) {
        this.kodeIdType = value;
    }

    /**
     * Gets the value of the kodeSamhType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeSamhType() {
        return kodeSamhType;
    }

    /**
     * Sets the value of the kodeSamhType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeSamhType(String value) {
        this.kodeSamhType = value;
    }

    /**
     * Gets the value of the kodeRelasjonRolle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeRelasjonRolle() {
        return kodeRelasjonRolle;
    }

    /**
     * Sets the value of the kodeRelasjonRolle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeRelasjonRolle(String value) {
        this.kodeRelasjonRolle = value;
    }

    /**
     * Gets the value of the datoRelFom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoRelFom() {
        return datoRelFom;
    }

    /**
     * Sets the value of the datoRelFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoRelFom(String value) {
        this.datoRelFom = value;
    }

    /**
     * Gets the value of the datoRelTom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoRelTom() {
        return datoRelTom;
    }

    /**
     * Sets the value of the datoRelTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoRelTom(String value) {
        this.datoRelTom = value;
    }

    /**
     * Gets the value of the gyldigRelasjon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGyldigRelasjon() {
        return gyldigRelasjon;
    }

    /**
     * Sets the value of the gyldigRelasjon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGyldigRelasjon(String value) {
        this.gyldigRelasjon = value;
    }

}
