//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 03:51:48 PM CET 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Typen beskriver alle feltene i en enkelt samhandlerrelasjon.
 * 
 * <p>Java class for Samhandler complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Samhandler"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.rtv.no/NamespaceTSS}typeSamhandlere"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="samhandler110" type="{http://www.rtv.no/NamespaceTSS}typeSamhandler"/&gt;
 *         &lt;element name="alternativId111" type="{http://www.rtv.no/NamespaceTSS}typeAltId"/&gt;
 *         &lt;element name="samhandlerFag120" type="{http://www.rtv.no/NamespaceTSS}typeSamhFag" minOccurs="0"/&gt;
 *         &lt;element name="samhandlerAvd125" type="{http://www.rtv.no/NamespaceTSS}typeSamhAvd" minOccurs="0"/&gt;
 *         &lt;element name="adresse130" type="{http://www.rtv.no/NamespaceTSS}typeSamhAdr" minOccurs="0"/&gt;
 *         &lt;element name="konto140" type="{http://www.rtv.no/NamespaceTSS}typeSamhKonto" minOccurs="0"/&gt;
 *         &lt;element name="kontakter150" type="{http://www.rtv.no/NamespaceTSS}typeSamhKontakt" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Samhandler", propOrder = {
    "samhandler110",
    "alternativId111",
    "samhandlerFag120",
    "samhandlerAvd125",
    "adresse130",
    "konto140",
    "kontakter150"
})
public class Samhandler
    extends TypeSamhandlere
{

    @XmlElement(required = true)
    protected TypeSamhandler samhandler110;
    @XmlElement(required = true)
    protected TypeAltId alternativId111;
    protected TypeSamhFag samhandlerFag120;
    protected TypeSamhAvd samhandlerAvd125;
    protected TypeSamhAdr adresse130;
    protected TypeSamhKonto konto140;
    protected TypeSamhKontakt kontakter150;

    /**
     * Gets the value of the samhandler110 property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSamhandler }
     *     
     */
    public TypeSamhandler getSamhandler110() {
        return samhandler110;
    }

    /**
     * Sets the value of the samhandler110 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSamhandler }
     *     
     */
    public void setSamhandler110(TypeSamhandler value) {
        this.samhandler110 = value;
    }

    /**
     * Gets the value of the alternativId111 property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAltId }
     *     
     */
    public TypeAltId getAlternativId111() {
        return alternativId111;
    }

    /**
     * Sets the value of the alternativId111 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAltId }
     *     
     */
    public void setAlternativId111(TypeAltId value) {
        this.alternativId111 = value;
    }

    /**
     * Gets the value of the samhandlerFag120 property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSamhFag }
     *     
     */
    public TypeSamhFag getSamhandlerFag120() {
        return samhandlerFag120;
    }

    /**
     * Sets the value of the samhandlerFag120 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSamhFag }
     *     
     */
    public void setSamhandlerFag120(TypeSamhFag value) {
        this.samhandlerFag120 = value;
    }

    /**
     * Gets the value of the samhandlerAvd125 property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSamhAvd }
     *     
     */
    public TypeSamhAvd getSamhandlerAvd125() {
        return samhandlerAvd125;
    }

    /**
     * Sets the value of the samhandlerAvd125 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSamhAvd }
     *     
     */
    public void setSamhandlerAvd125(TypeSamhAvd value) {
        this.samhandlerAvd125 = value;
    }

    /**
     * Gets the value of the adresse130 property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSamhAdr }
     *     
     */
    public TypeSamhAdr getAdresse130() {
        return adresse130;
    }

    /**
     * Sets the value of the adresse130 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSamhAdr }
     *     
     */
    public void setAdresse130(TypeSamhAdr value) {
        this.adresse130 = value;
    }

    /**
     * Gets the value of the konto140 property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSamhKonto }
     *     
     */
    public TypeSamhKonto getKonto140() {
        return konto140;
    }

    /**
     * Sets the value of the konto140 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSamhKonto }
     *     
     */
    public void setKonto140(TypeSamhKonto value) {
        this.konto140 = value;
    }

    /**
     * Gets the value of the kontakter150 property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSamhKontakt }
     *     
     */
    public TypeSamhKontakt getKontakter150() {
        return kontakter150;
    }

    /**
     * Sets the value of the kontakter150 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSamhKontakt }
     *     
     */
    public void setKontakter150(TypeSamhKontakt value) {
        this.kontakter150 = value;
    }

}
