//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Inneholder elementene som skal være med i en 160-rekord ved oppdatering
 * 
 * <p>Java class for samhAjour160Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="samhAjour160Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="avdNr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="kodeApnTidType" type="{http://www.rtv.no/NamespaceTSS}Tkodeapntidtype"/>
 *         <element name="kodeApnPeriode" type="{http://www.rtv.no/NamespaceTSS}Tkodeapnperiode"/>
 *         <element name="apningsTidFom" type="{http://www.rtv.no/NamespaceTSS}Thhmmss"/>
 *         <element name="apningsTidTom" type="{http://www.rtv.no/NamespaceTSS}Thhmmss"/>
 *         <element name="datoApningFom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="datoApningTom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="gyldigApning" type="{http://www.rtv.no/NamespaceTSS}Tgyldig"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samhAjour160Type", propOrder = {
    "avdNr",
    "kodeApnTidType",
    "kodeApnPeriode",
    "apningsTidFom",
    "apningsTidTom",
    "datoApningFom",
    "datoApningTom",
    "gyldigApning"
})
public class SamhAjour160Type {

    @XmlElement(required = true)
    protected String avdNr;
    @XmlElement(required = true)
    protected String kodeApnTidType;
    @XmlElement(required = true)
    protected String kodeApnPeriode;
    @XmlElement(required = true)
    protected String apningsTidFom;
    @XmlElement(required = true)
    protected String apningsTidTom;
    @XmlElement(required = true)
    protected String datoApningFom;
    @XmlElement(required = true)
    protected String datoApningTom;
    @XmlElement(required = true)
    protected String gyldigApning;

    /**
     * Gets the value of the avdNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvdNr() {
        return avdNr;
    }

    /**
     * Sets the value of the avdNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvdNr(String value) {
        this.avdNr = value;
    }

    /**
     * Gets the value of the kodeApnTidType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeApnTidType() {
        return kodeApnTidType;
    }

    /**
     * Sets the value of the kodeApnTidType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeApnTidType(String value) {
        this.kodeApnTidType = value;
    }

    /**
     * Gets the value of the kodeApnPeriode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeApnPeriode() {
        return kodeApnPeriode;
    }

    /**
     * Sets the value of the kodeApnPeriode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeApnPeriode(String value) {
        this.kodeApnPeriode = value;
    }

    /**
     * Gets the value of the apningsTidFom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApningsTidFom() {
        return apningsTidFom;
    }

    /**
     * Sets the value of the apningsTidFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApningsTidFom(String value) {
        this.apningsTidFom = value;
    }

    /**
     * Gets the value of the apningsTidTom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApningsTidTom() {
        return apningsTidTom;
    }

    /**
     * Sets the value of the apningsTidTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApningsTidTom(String value) {
        this.apningsTidTom = value;
    }

    /**
     * Gets the value of the datoApningFom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoApningFom() {
        return datoApningFom;
    }

    /**
     * Sets the value of the datoApningFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoApningFom(String value) {
        this.datoApningFom = value;
    }

    /**
     * Gets the value of the datoApningTom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoApningTom() {
        return datoApningTom;
    }

    /**
     * Sets the value of the datoApningTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoApningTom(String value) {
        this.datoApningTom = value;
    }

    /**
     * Gets the value of the gyldigApning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGyldigApning() {
        return gyldigApning;
    }

    /**
     * Sets the value of the gyldigApning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGyldigApning(String value) {
        this.gyldigApning = value;
    }

}
