//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Inneholder elementene som skal være med i en 111-rekord ved oppdatering
 * 
 * <p>Java class for samhAjour111Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="samhAjour111Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="idAlternativ">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <length value="11"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="kodeAltIdentType" type="{http://www.rtv.no/NamespaceTSS}TkodeIdenttype"/>
 *         <element name="datoIdentFom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="datoIdentTom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="gyldigIdent" type="{http://www.rtv.no/NamespaceTSS}Tgyldig"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samhAjour111Type", propOrder = {
    "idAlternativ",
    "kodeAltIdentType",
    "datoIdentFom",
    "datoIdentTom",
    "gyldigIdent"
})
public class SamhAjour111Type {

    @XmlElement(required = true)
    protected String idAlternativ;
    @XmlElement(required = true)
    protected String kodeAltIdentType;
    @XmlElement(required = true)
    protected String datoIdentFom;
    @XmlElement(required = true)
    protected String datoIdentTom;
    @XmlElement(required = true)
    protected String gyldigIdent;

    /**
     * Gets the value of the idAlternativ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAlternativ() {
        return idAlternativ;
    }

    /**
     * Sets the value of the idAlternativ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAlternativ(String value) {
        this.idAlternativ = value;
    }

    /**
     * Gets the value of the kodeAltIdentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeAltIdentType() {
        return kodeAltIdentType;
    }

    /**
     * Sets the value of the kodeAltIdentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeAltIdentType(String value) {
        this.kodeAltIdentType = value;
    }

    /**
     * Gets the value of the datoIdentFom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoIdentFom() {
        return datoIdentFom;
    }

    /**
     * Sets the value of the datoIdentFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoIdentFom(String value) {
        this.datoIdentFom = value;
    }

    /**
     * Gets the value of the datoIdentTom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoIdentTom() {
        return datoIdentTom;
    }

    /**
     * Sets the value of the datoIdentTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoIdentTom(String value) {
        this.datoIdentTom = value;
    }

    /**
     * Gets the value of the gyldigIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGyldigIdent() {
        return gyldigIdent;
    }

    /**
     * Sets the value of the gyldigIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGyldigIdent(String value) {
        this.gyldigIdent = value;
    }

}
