//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Inneholder elementene som skal være med i en 170-rekord ved oppdatering
 * 
 * <p>Java class for samhAjour170Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="samhAjour170Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="kodeAutorType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="datoAutorFom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="datoAutorTom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/>
 *         <element name="autorId">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="0"/>
 *               <maxLength value="15"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="gyldigAutor" type="{http://www.rtv.no/NamespaceTSS}Tgyldig"/>
 *         <element name="autorRettInfo" type="{http://www.rtv.no/NamespaceTSS}TAutorRettInfo" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samhAjour170Type", propOrder = {
    "kodeAutorType",
    "datoAutorFom",
    "datoAutorTom",
    "autorId",
    "gyldigAutor",
    "autorRettInfo"
})
public class SamhAjour170Type {

    @XmlElement(required = true)
    protected String kodeAutorType;
    @XmlElement(required = true)
    protected String datoAutorFom;
    @XmlElement(required = true)
    protected String datoAutorTom;
    @XmlElement(required = true)
    protected String autorId;
    @XmlElement(required = true)
    protected String gyldigAutor;
    protected TAutorRettInfo autorRettInfo;

    /**
     * Gets the value of the kodeAutorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeAutorType() {
        return kodeAutorType;
    }

    /**
     * Sets the value of the kodeAutorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeAutorType(String value) {
        this.kodeAutorType = value;
    }

    /**
     * Gets the value of the datoAutorFom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoAutorFom() {
        return datoAutorFom;
    }

    /**
     * Sets the value of the datoAutorFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoAutorFom(String value) {
        this.datoAutorFom = value;
    }

    /**
     * Gets the value of the datoAutorTom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoAutorTom() {
        return datoAutorTom;
    }

    /**
     * Sets the value of the datoAutorTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoAutorTom(String value) {
        this.datoAutorTom = value;
    }

    /**
     * Gets the value of the autorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutorId() {
        return autorId;
    }

    /**
     * Sets the value of the autorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutorId(String value) {
        this.autorId = value;
    }

    /**
     * Gets the value of the gyldigAutor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGyldigAutor() {
        return gyldigAutor;
    }

    /**
     * Sets the value of the gyldigAutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGyldigAutor(String value) {
        this.gyldigAutor = value;
    }

    /**
     * Gets the value of the autorRettInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TAutorRettInfo }
     *     
     */
    public TAutorRettInfo getAutorRettInfo() {
        return autorRettInfo;
    }

    /**
     * Sets the value of the autorRettInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAutorRettInfo }
     *     
     */
    public void setAutorRettInfo(TAutorRettInfo value) {
        this.autorRettInfo = value;
    }

}
