//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 03:51:48 PM CET 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Inneholder elementene som skal være med i en 195-rekord ved oppdatering
 * 
 * <p>Java class for samhAjour195Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="samhAjour195Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idOff" type="{http://www.rtv.no/NamespaceTSS}Tidoff"/&gt;
 *         &lt;element name="kodeIdType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.rtv.no/NamespaceTSS}TkodeIdenttype"&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="kodeSamhType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kodeAvtaleType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.rtv.no/NamespaceTSS}Tkodeavtaletype"&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="kodeAvtaleRett" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="datoAvtaleRettFom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/&gt;
 *         &lt;element name="datoAvtaleRettTom" type="{http://www.rtv.no/NamespaceTSS}Tdato"/&gt;
 *         &lt;element name="gyldigAvtaleRett" type="{http://www.rtv.no/NamespaceTSS}Tgyldig"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samhAjour195Type", propOrder = {
    "idOff",
    "kodeIdType",
    "kodeSamhType",
    "kodeAvtaleType",
    "kodeAvtaleRett",
    "datoAvtaleRettFom",
    "datoAvtaleRettTom",
    "gyldigAvtaleRett"
})
public class SamhAjour195Type {

    @XmlElement(required = true)
    protected String idOff;
    @XmlElement(required = true)
    protected String kodeIdType;
    @XmlElement(required = true)
    protected String kodeSamhType;
    @XmlElement(required = true)
    protected String kodeAvtaleType;
    @XmlElement(required = true)
    protected String kodeAvtaleRett;
    @XmlElement(required = true)
    protected String datoAvtaleRettFom;
    @XmlElement(required = true)
    protected String datoAvtaleRettTom;
    @XmlElement(required = true)
    protected String gyldigAvtaleRett;

    /**
     * Gets the value of the idOff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdOff() {
        return idOff;
    }

    /**
     * Sets the value of the idOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdOff(String value) {
        this.idOff = value;
    }

    /**
     * Gets the value of the kodeIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeIdType() {
        return kodeIdType;
    }

    /**
     * Sets the value of the kodeIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeIdType(String value) {
        this.kodeIdType = value;
    }

    /**
     * Gets the value of the kodeSamhType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeSamhType() {
        return kodeSamhType;
    }

    /**
     * Sets the value of the kodeSamhType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeSamhType(String value) {
        this.kodeSamhType = value;
    }

    /**
     * Gets the value of the kodeAvtaleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeAvtaleType() {
        return kodeAvtaleType;
    }

    /**
     * Sets the value of the kodeAvtaleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeAvtaleType(String value) {
        this.kodeAvtaleType = value;
    }

    /**
     * Gets the value of the kodeAvtaleRett property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeAvtaleRett() {
        return kodeAvtaleRett;
    }

    /**
     * Sets the value of the kodeAvtaleRett property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeAvtaleRett(String value) {
        this.kodeAvtaleRett = value;
    }

    /**
     * Gets the value of the datoAvtaleRettFom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoAvtaleRettFom() {
        return datoAvtaleRettFom;
    }

    /**
     * Sets the value of the datoAvtaleRettFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoAvtaleRettFom(String value) {
        this.datoAvtaleRettFom = value;
    }

    /**
     * Gets the value of the datoAvtaleRettTom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatoAvtaleRettTom() {
        return datoAvtaleRettTom;
    }

    /**
     * Sets the value of the datoAvtaleRettTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoAvtaleRettTom(String value) {
        this.datoAvtaleRettTom = value;
    }

    /**
     * Gets the value of the gyldigAvtaleRett property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGyldigAvtaleRett() {
        return gyldigAvtaleRett;
    }

    /**
     * Sets the value of the gyldigAvtaleRett property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGyldigAvtaleRett(String value) {
        this.gyldigAvtaleRett = value;
    }

}
