//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Inneholder elementene som skal være med ved spørring mot 985
 * 
 * <p>Java class for samhandlerIDataB986Type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="samhandlerIDataB986Type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="typeGironr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="giroNummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="brukerID" type="{http://www.rtv.no/NamespaceTSS}Tbrukerid"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samhandlerIDataB986Type", propOrder = {
    "typeGironr",
    "giroNummer",
    "brukerID"
})
public class SamhandlerIDataB986Type {

    @XmlElement(required = true)
    protected String typeGironr;
    @XmlElement(required = true)
    protected String giroNummer;
    /**
     * Dette feltet skal ikke fylles ut av en bruker i et skjermbilde.
     * 
     */
    @XmlElement(required = true)
    protected String brukerID;

    /**
     * Gets the value of the typeGironr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeGironr() {
        return typeGironr;
    }

    /**
     * Sets the value of the typeGironr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeGironr(String value) {
        this.typeGironr = value;
    }

    /**
     * Gets the value of the giroNummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiroNummer() {
        return giroNummer;
    }

    /**
     * Sets the value of the giroNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiroNummer(String value) {
        this.giroNummer = value;
    }

    /**
     * Dette feltet skal ikke fylles ut av en bruker i et skjermbilde.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrukerID() {
        return brukerID;
    }

    /**
     * Sets the value of the brukerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getBrukerID()
     */
    public void setBrukerID(String value) {
        this.brukerID = value;
    }

}
