//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TServicerutiner complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TServicerutiner">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="samhandlerIDataB910" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB910Type"/>
 *         <element name="samhandlerIDataB920" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB91AType"/>
 *         <element name="samhandlerIDataB930" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB91AType"/>
 *         <element name="samhandlerIDataB931" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB931Type"/>
 *         <element name="samhandlerIDataB940" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB940Type"/>
 *         <element name="samhandlerIDataB950" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB910Type"/>
 *         <element name="samhandlerIDataB960" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB910Type"/>
 *         <element name="samhandlerIDataB961" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB961Type"/>
 *         <element name="samhandlerIDataB980" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB980Type"/>
 *         <element name="samhandlerIDataB985" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB985Type"/>
 *         <element name="samhandlerIDataB98A" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB98AType"/>
 *         <element name="samhandlerIDataB986" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB986Type"/>
 *         <element name="samhandlerIDataB990" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB990Type"/>
 *         <element name="samhandlerIDataB992" type="{http://www.rtv.no/NamespaceTSS}samhandlerIDataB992Type"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TServicerutiner", propOrder = {
    "samhandlerIDataB910",
    "samhandlerIDataB920",
    "samhandlerIDataB930",
    "samhandlerIDataB931",
    "samhandlerIDataB940",
    "samhandlerIDataB950",
    "samhandlerIDataB960",
    "samhandlerIDataB961",
    "samhandlerIDataB980",
    "samhandlerIDataB985",
    "samhandlerIDataB98A",
    "samhandlerIDataB986",
    "samhandlerIDataB990",
    "samhandlerIDataB992"
})
public class TServicerutiner {

    protected SamhandlerIDataB910Type samhandlerIDataB910;
    protected SamhandlerIDataB91AType samhandlerIDataB920;
    protected SamhandlerIDataB91AType samhandlerIDataB930;
    protected SamhandlerIDataB931Type samhandlerIDataB931;
    protected SamhandlerIDataB940Type samhandlerIDataB940;
    protected SamhandlerIDataB910Type samhandlerIDataB950;
    protected SamhandlerIDataB910Type samhandlerIDataB960;
    protected SamhandlerIDataB961Type samhandlerIDataB961;
    protected SamhandlerIDataB980Type samhandlerIDataB980;
    protected SamhandlerIDataB985Type samhandlerIDataB985;
    protected SamhandlerIDataB98AType samhandlerIDataB98A;
    protected SamhandlerIDataB986Type samhandlerIDataB986;
    protected SamhandlerIDataB990Type samhandlerIDataB990;
    protected SamhandlerIDataB992Type samhandlerIDataB992;

    /**
     * Gets the value of the samhandlerIDataB910 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB910Type }
     *     
     */
    public SamhandlerIDataB910Type getSamhandlerIDataB910() {
        return samhandlerIDataB910;
    }

    /**
     * Sets the value of the samhandlerIDataB910 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB910Type }
     *     
     */
    public void setSamhandlerIDataB910(SamhandlerIDataB910Type value) {
        this.samhandlerIDataB910 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB920 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB91AType }
     *     
     */
    public SamhandlerIDataB91AType getSamhandlerIDataB920() {
        return samhandlerIDataB920;
    }

    /**
     * Sets the value of the samhandlerIDataB920 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB91AType }
     *     
     */
    public void setSamhandlerIDataB920(SamhandlerIDataB91AType value) {
        this.samhandlerIDataB920 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB930 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB91AType }
     *     
     */
    public SamhandlerIDataB91AType getSamhandlerIDataB930() {
        return samhandlerIDataB930;
    }

    /**
     * Sets the value of the samhandlerIDataB930 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB91AType }
     *     
     */
    public void setSamhandlerIDataB930(SamhandlerIDataB91AType value) {
        this.samhandlerIDataB930 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB931 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB931Type }
     *     
     */
    public SamhandlerIDataB931Type getSamhandlerIDataB931() {
        return samhandlerIDataB931;
    }

    /**
     * Sets the value of the samhandlerIDataB931 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB931Type }
     *     
     */
    public void setSamhandlerIDataB931(SamhandlerIDataB931Type value) {
        this.samhandlerIDataB931 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB940 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB940Type }
     *     
     */
    public SamhandlerIDataB940Type getSamhandlerIDataB940() {
        return samhandlerIDataB940;
    }

    /**
     * Sets the value of the samhandlerIDataB940 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB940Type }
     *     
     */
    public void setSamhandlerIDataB940(SamhandlerIDataB940Type value) {
        this.samhandlerIDataB940 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB950 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB910Type }
     *     
     */
    public SamhandlerIDataB910Type getSamhandlerIDataB950() {
        return samhandlerIDataB950;
    }

    /**
     * Sets the value of the samhandlerIDataB950 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB910Type }
     *     
     */
    public void setSamhandlerIDataB950(SamhandlerIDataB910Type value) {
        this.samhandlerIDataB950 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB960 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB910Type }
     *     
     */
    public SamhandlerIDataB910Type getSamhandlerIDataB960() {
        return samhandlerIDataB960;
    }

    /**
     * Sets the value of the samhandlerIDataB960 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB910Type }
     *     
     */
    public void setSamhandlerIDataB960(SamhandlerIDataB910Type value) {
        this.samhandlerIDataB960 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB961 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB961Type }
     *     
     */
    public SamhandlerIDataB961Type getSamhandlerIDataB961() {
        return samhandlerIDataB961;
    }

    /**
     * Sets the value of the samhandlerIDataB961 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB961Type }
     *     
     */
    public void setSamhandlerIDataB961(SamhandlerIDataB961Type value) {
        this.samhandlerIDataB961 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB980 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB980Type }
     *     
     */
    public SamhandlerIDataB980Type getSamhandlerIDataB980() {
        return samhandlerIDataB980;
    }

    /**
     * Sets the value of the samhandlerIDataB980 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB980Type }
     *     
     */
    public void setSamhandlerIDataB980(SamhandlerIDataB980Type value) {
        this.samhandlerIDataB980 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB985 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB985Type }
     *     
     */
    public SamhandlerIDataB985Type getSamhandlerIDataB985() {
        return samhandlerIDataB985;
    }

    /**
     * Sets the value of the samhandlerIDataB985 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB985Type }
     *     
     */
    public void setSamhandlerIDataB985(SamhandlerIDataB985Type value) {
        this.samhandlerIDataB985 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB98A property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB98AType }
     *     
     */
    public SamhandlerIDataB98AType getSamhandlerIDataB98A() {
        return samhandlerIDataB98A;
    }

    /**
     * Sets the value of the samhandlerIDataB98A property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB98AType }
     *     
     */
    public void setSamhandlerIDataB98A(SamhandlerIDataB98AType value) {
        this.samhandlerIDataB98A = value;
    }

    /**
     * Gets the value of the samhandlerIDataB986 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB986Type }
     *     
     */
    public SamhandlerIDataB986Type getSamhandlerIDataB986() {
        return samhandlerIDataB986;
    }

    /**
     * Sets the value of the samhandlerIDataB986 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB986Type }
     *     
     */
    public void setSamhandlerIDataB986(SamhandlerIDataB986Type value) {
        this.samhandlerIDataB986 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB990 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB990Type }
     *     
     */
    public SamhandlerIDataB990Type getSamhandlerIDataB990() {
        return samhandlerIDataB990;
    }

    /**
     * Sets the value of the samhandlerIDataB990 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB990Type }
     *     
     */
    public void setSamhandlerIDataB990(SamhandlerIDataB990Type value) {
        this.samhandlerIDataB990 = value;
    }

    /**
     * Gets the value of the samhandlerIDataB992 property.
     * 
     * @return
     *     possible object is
     *     {@link SamhandlerIDataB992Type }
     *     
     */
    public SamhandlerIDataB992Type getSamhandlerIDataB992() {
        return samhandlerIDataB992;
    }

    /**
     * Sets the value of the samhandlerIDataB992 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamhandlerIDataB992Type }
     *     
     */
    public void setSamhandlerIDataB992(SamhandlerIDataB992Type value) {
        this.samhandlerIDataB992 = value;
    }

}
