//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 03:51:48 PM CET 
//


package no.rtv.namespacetss;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Her beskrives returfeltene fra 931
 * 
 * <p>Java class for typeOD931 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeOD931"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="antallSamhandlere" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="enkeltSamhandler" type="{http://www.rtv.no/NamespaceTSS}typeRel931" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeOD931", propOrder = {
    "antallSamhandlere",
    "enkeltSamhandler"
})
public class TypeOD931 {

    @XmlElement(required = true)
    protected String antallSamhandlere;
    protected List<TypeRel931> enkeltSamhandler;

    /**
     * Gets the value of the antallSamhandlere property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntallSamhandlere() {
        return antallSamhandlere;
    }

    /**
     * Sets the value of the antallSamhandlere property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntallSamhandlere(String value) {
        this.antallSamhandlere = value;
    }

    /**
     * Gets the value of the enkeltSamhandler property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the enkeltSamhandler property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnkeltSamhandler().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeRel931 }
     * 
     * 
     */
    public List<TypeRel931> getEnkeltSamhandler() {
        if (enkeltSamhandler == null) {
            enkeltSamhandler = new ArrayList<TypeRel931>();
        }
        return this.enkeltSamhandler;
    }

}
