//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 03:51:48 PM CET 
//


package no.rtv.namespacetss;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Avdeling - praksis til en samhandler
 * 
 * <p>Java class for typeApning complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeApning"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="antATider" type="{http://www.rtv.no/NamespaceTSS}Tantallforekomster"/&gt;
 *         &lt;element name="apningsTider" type="{http://www.rtv.no/NamespaceTSS}TapningTid" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeApning", propOrder = {
    "antATider",
    "apningsTider"
})
public class TypeApning {

    protected String antATider;
    protected List<TapningTid> apningsTider;

    /**
     * Gets the value of the antATider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntATider() {
        return antATider;
    }

    /**
     * Sets the value of the antATider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntATider(String value) {
        this.antATider = value;
    }

    /**
     * Gets the value of the apningsTider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the apningsTider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApningsTider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TapningTid }
     * 
     * 
     */
    public List<TapningTid> getApningsTider() {
        if (apningsTider == null) {
            apningsTider = new ArrayList<TapningTid>();
        }
        return this.apningsTider;
    }

}
