//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Typen beskriver alle feltene i en enkelt samhandlerrelasjon.
 * 
 * <p>Java class for typeRelasjoner complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="typeRelasjoner">
 *   <complexContent>
 *     <extension base="{http://www.rtv.no/NamespaceTSS}typeRelAvt">
 *       <sequence>
 *         <element name="samhandler110" type="{http://www.rtv.no/NamespaceTSS}typeSamhandler"/>
 *         <element name="relasjoner180" type="{http://www.rtv.no/NamespaceTSS}typeRelAvtaler"/>
 *         <element name="avtaler190" type="{http://www.rtv.no/NamespaceTSS}typeAvtaler"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeRelasjoner", propOrder = {
    "samhandler110",
    "relasjoner180",
    "avtaler190"
})
public class TypeRelasjoner
    extends TypeRelAvt
{

    @XmlElement(required = true)
    protected TypeSamhandler samhandler110;
    @XmlElement(required = true)
    protected TypeRelAvtaler relasjoner180;
    @XmlElement(required = true)
    protected TypeAvtaler avtaler190;

    /**
     * Gets the value of the samhandler110 property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSamhandler }
     *     
     */
    public TypeSamhandler getSamhandler110() {
        return samhandler110;
    }

    /**
     * Sets the value of the samhandler110 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSamhandler }
     *     
     */
    public void setSamhandler110(TypeSamhandler value) {
        this.samhandler110 = value;
    }

    /**
     * Gets the value of the relasjoner180 property.
     * 
     * @return
     *     possible object is
     *     {@link TypeRelAvtaler }
     *     
     */
    public TypeRelAvtaler getRelasjoner180() {
        return relasjoner180;
    }

    /**
     * Sets the value of the relasjoner180 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeRelAvtaler }
     *     
     */
    public void setRelasjoner180(TypeRelAvtaler value) {
        this.relasjoner180 = value;
    }

    /**
     * Gets the value of the avtaler190 property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAvtaler }
     *     
     */
    public TypeAvtaler getAvtaler190() {
        return avtaler190;
    }

    /**
     * Sets the value of the avtaler190 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAvtaler }
     *     
     */
    public void setAvtaler190(TypeAvtaler value) {
        this.avtaler190 = value;
    }

}
