//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Avdeling - praksis til en samhandler
 * 
 * <p>Java class for typeSamhAvd complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="typeSamhAvd">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence minOccurs="0">
 *         <element name="antSamhAvd" type="{http://www.rtv.no/NamespaceTSS}Tantallforekomster"/>
 *         <element name="samhAvd" type="{http://www.rtv.no/NamespaceTSS}samhAvdPraType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeSamhAvd", propOrder = {
    "antSamhAvd",
    "samhAvd"
})
public class TypeSamhAvd {

    protected String antSamhAvd;
    protected List<SamhAvdPraType> samhAvd;

    /**
     * Gets the value of the antSamhAvd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntSamhAvd() {
        return antSamhAvd;
    }

    /**
     * Sets the value of the antSamhAvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntSamhAvd(String value) {
        this.antSamhAvd = value;
    }

    /**
     * Gets the value of the samhAvd property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the samhAvd property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getSamhAvd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SamhAvdPraType }
     * </p>
     * 
     * 
     * @return
     *     The value of the samhAvd property.
     */
    public List<SamhAvdPraType> getSamhAvd() {
        if (samhAvd == null) {
            samhAvd = new ArrayList<>();
        }
        return this.samhAvd;
    }

}
