//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Adresseopplysninger til en samhandler
 * 
 * <p>Java class for typeSamhAdr complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="typeSamhAdr">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="antAdresse" type="{http://www.rtv.no/NamespaceTSS}Tantallforekomster"/>
 *         <element name="adresseSamh" type="{http://www.rtv.no/NamespaceTSS}adresseSamhType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeSamhAdr", propOrder = {
    "antAdresse",
    "adresseSamh"
})
public class TypeSamhAdr {

    @XmlElement(required = true)
    protected String antAdresse;
    protected List<AdresseSamhType> adresseSamh;

    /**
     * Gets the value of the antAdresse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntAdresse() {
        return antAdresse;
    }

    /**
     * Sets the value of the antAdresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntAdresse(String value) {
        this.antAdresse = value;
    }

    /**
     * Gets the value of the adresseSamh property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adresseSamh property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAdresseSamh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdresseSamhType }
     * </p>
     * 
     * 
     * @return
     *     The value of the adresseSamh property.
     */
    public List<AdresseSamhType> getAdresseSamh() {
        if (adresseSamh == null) {
            adresseSamh = new ArrayList<>();
        }
        return this.adresseSamh;
    }

}
