//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 03:51:48 PM CET 
//


package no.rtv.namespacetss;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Autorisasjon til samhandler
 * 
 * <p>Java class for typeAutorisasjon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeAutorisasjon"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="antAutorInfo" type="{http://www.rtv.no/NamespaceTSS}Tantallforekomster"/&gt;
 *         &lt;element name="autorisasjon" type="{http://www.rtv.no/NamespaceTSS}autorisasjonType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeAutorisasjon", propOrder = {
    "antAutorInfo",
    "autorisasjon"
})
public class TypeAutorisasjon {

    protected String antAutorInfo;
    protected List<AutorisasjonType> autorisasjon;

    /**
     * Gets the value of the antAutorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntAutorInfo() {
        return antAutorInfo;
    }

    /**
     * Sets the value of the antAutorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntAutorInfo(String value) {
        this.antAutorInfo = value;
    }

    /**
     * Gets the value of the autorisasjon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the autorisasjon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAutorisasjon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AutorisasjonType }
     * 
     * 
     */
    public List<AutorisasjonType> getAutorisasjon() {
        if (autorisasjon == null) {
            autorisasjon = new ArrayList<AutorisasjonType>();
        }
        return this.autorisasjon;
    }

}
