//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.rtv.namespacetss;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Kontoopplysninger for en samhandler
 * 
 * <p>Java class for typeSamhKonto complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="typeSamhKonto">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="antKonto" type="{http://www.rtv.no/NamespaceTSS}Tantallforekomster"/>
 *         <element name="konto" type="{http://www.rtv.no/NamespaceTSS}kontoType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeSamhKonto", propOrder = {
    "antKonto",
    "konto"
})
public class TypeSamhKonto {

    @XmlElement(required = true)
    protected String antKonto;
    protected List<KontoType> konto;

    /**
     * Gets the value of the antKonto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntKonto() {
        return antKonto;
    }

    /**
     * Sets the value of the antKonto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntKonto(String value) {
        this.antKonto = value;
    }

    /**
     * Gets the value of the konto property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the konto property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getKonto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KontoType }
     * </p>
     * 
     * 
     * @return
     *     The value of the konto property.
     */
    public List<KontoType> getKonto() {
        if (konto == null) {
            konto = new ArrayList<>();
        }
        return this.konto;
    }

}
