
package no.nav.system.os.tjenester.simulerfpservice.simulerfpservicegrensesnitt;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.3
 * 2025-09-05T10:02:16.205+02:00
 * Generated source version: 4.1.3
 */

@WebFault(name = "sendInnOppdragFeilUnderBehandling", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt")
public class SendInnOppdragFeilUnderBehandling extends Exception {

    private no.nav.system.os.tjenester.simulerfpservice.feil.FeilUnderBehandling faultInfo;

    public SendInnOppdragFeilUnderBehandling() {
        super();
    }

    public SendInnOppdragFeilUnderBehandling(String message) {
        super(message);
    }

    public SendInnOppdragFeilUnderBehandling(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SendInnOppdragFeilUnderBehandling(String message, no.nav.system.os.tjenester.simulerfpservice.feil.FeilUnderBehandling sendInnOppdragFeilUnderBehandling) {
        super(message);
        this.faultInfo = sendInnOppdragFeilUnderBehandling;
    }

    public SendInnOppdragFeilUnderBehandling(String message, no.nav.system.os.tjenester.simulerfpservice.feil.FeilUnderBehandling sendInnOppdragFeilUnderBehandling, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = sendInnOppdragFeilUnderBehandling;
    }

    public no.nav.system.os.tjenester.simulerfpservice.feil.FeilUnderBehandling getFaultInfo() {
        return this.faultInfo;
    }
}
