package no.nav.system.os.tjenester.simulerfpservice.simulerfpservicegrensesnitt;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-04-24T22:50:56.997+02:00
 * Generated source version: 4.1.1
 *
 */
@WebService(targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt", name = "simulerFpService")
@XmlSeeAlso({no.nav.system.os.entiteter.infomelding.ObjectFactory.class, no.nav.system.os.entiteter.oppdragskjema.ObjectFactory.class, no.nav.system.os.entiteter.typer.simpletypes.ObjectFactory.class, no.nav.system.os.tjenester.simulerfpservice.simulerfpserviceservicetypes.ObjectFactory.class, ObjectFactory.class, no.nav.system.os.entiteter.beregningskjema.ObjectFactory.class, no.nav.system.os.tjenester.simulerfpservice.feil.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SimulerFpService {

    /**
     * Operasjonen tilbyr simuleringsberegning
     */
    @WebMethod
    @WebResult(name = "simulerBeregningResponse", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt", partName = "parameters")
    public SimulerBeregningResponse simulerBeregning(

        @WebParam(partName = "parameters", name = "simulerBeregningRequest", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt")
        SimulerBeregningRequest parameters
    ) throws SimulerBeregningFeilUnderBehandling;

    /**
     * Operasjonen tilbyr innsending og registrering av ny/endret oppdrag som følge av nytt/endring på vedtak
     */
    @WebMethod
    @WebResult(name = "sendInnOppdragResponse", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt", partName = "parameters")
    public SendInnOppdragResponse sendInnOppdrag(

        @WebParam(partName = "parameters", name = "sendInnOppdragRequest", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt")
        SendInnOppdragRequest parameters
    ) throws SendInnOppdragFeilUnderBehandling;
}
