package no.nav.okonomi.tilbakekrevingservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-04-24T22:50:53.994+02:00
 * Generated source version: 4.1.1
 *
 */
@WebService(targetNamespace = "http://okonomi.nav.no/tilbakekrevingService/", name = "TilbakekrevingPortType")
@XmlSeeAlso({no.nav.tilbakekreving.kravgrunnlag.annuller.v1.ObjectFactory.class, no.nav.tilbakekreving.kravgrunnlag.detalj.v1.ObjectFactory.class, ObjectFactory.class, no.nav.tilbakekreving.tilbakekrevingsvedtak.vedtak.v1.ObjectFactory.class, no.nav.tilbakekreving.kravgrunnlag.hentliste.v1.ObjectFactory.class, no.nav.tilbakekreving.typer.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TilbakekrevingPortType {

    @WebMethod(action = "http://okonomi.nav.no/tilbakekrevingService/TilbakekrevingPortType/tilbakekrevingsvedtakRequest")
    @WebResult(name = "tilbakekrevingsvedtakResponse", targetNamespace = "http://okonomi.nav.no/tilbakekrevingService/", partName = "response")
    public TilbakekrevingsvedtakResponse tilbakekrevingsvedtak(

        @WebParam(partName = "request", name = "tilbakekrevingsvedtakRequest", targetNamespace = "http://okonomi.nav.no/tilbakekrevingService/")
        TilbakekrevingsvedtakRequest request
    );

    @WebMethod(action = "http://okonomi.nav.no/tilbakekrevingService/TilbakekrevingPortType/kravgrunnlagAnnulerRequest")
    @WebResult(name = "kravgrunnlagAnnulerResponse", targetNamespace = "http://okonomi.nav.no/tilbakekrevingService/", partName = "response")
    public KravgrunnlagAnnulerResponse kravgrunnlagAnnuler(

        @WebParam(partName = "request", name = "kravgrunnlagAnnulerRequest", targetNamespace = "http://okonomi.nav.no/tilbakekrevingService/")
        KravgrunnlagAnnulerRequest request
    );

    @WebMethod(action = "http://okonomi.nav.no/tilbakekrevingService/TilbakekrevingPortType/kravgrunnlagHentDetaljRequest")
    @WebResult(name = "kravgrunnlagHentDetaljResponse", targetNamespace = "http://okonomi.nav.no/tilbakekrevingService/", partName = "response")
    public KravgrunnlagHentDetaljResponse kravgrunnlagHentDetalj(

        @WebParam(partName = "request", name = "kravgrunnlagHentDetaljRequest", targetNamespace = "http://okonomi.nav.no/tilbakekrevingService/")
        KravgrunnlagHentDetaljRequest request
    );

    @WebMethod(action = "http://okonomi.nav.no/tilbakekrevingService/TilbakekrevingPortType/kravgrunnlagHentListeRequest")
    @WebResult(name = "kravgrunnlagHentListeResponse", targetNamespace = "http://okonomi.nav.no/tilbakekrevingService/", partName = "response")
    public KravgrunnlagHentListeResponse kravgrunnlagHentListe(

        @WebParam(partName = "request", name = "kravgrunnlagHentListeRequest", targetNamespace = "http://okonomi.nav.no/tilbakekrevingService/")
        KravgrunnlagHentListeRequest request
    );
}
