
package no.nav.okonomi.tilbakekrevingservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TilbakekrevingService", targetNamespace = "http://okonomi.nav.no/tilbakekrevingService/", wsdlLocation = "file:/Users/johan/proj/other/tjenestespesifikasjoner/tilbakekreving-v1-tjenestespesifikasjon/src/main/wsdl/no/nav/tilbakekreving/tilbakekreving-v1-tjenestespesifikasjon.wsdl")
public class TilbakekrevingService
    extends Service
{

    private final static URL TILBAKEKREVINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException TILBAKEKREVINGSERVICE_EXCEPTION;
    private final static QName TILBAKEKREVINGSERVICE_QNAME = new QName("http://okonomi.nav.no/tilbakekrevingService/", "TilbakekrevingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/johan/proj/other/tjenestespesifikasjoner/tilbakekreving-v1-tjenestespesifikasjon/src/main/wsdl/no/nav/tilbakekreving/tilbakekreving-v1-tjenestespesifikasjon.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TILBAKEKREVINGSERVICE_WSDL_LOCATION = url;
        TILBAKEKREVINGSERVICE_EXCEPTION = e;
    }

    public TilbakekrevingService() {
        super(__getWsdlLocation(), TILBAKEKREVINGSERVICE_QNAME);
    }

    public TilbakekrevingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TILBAKEKREVINGSERVICE_QNAME, features);
    }

    public TilbakekrevingService(URL wsdlLocation) {
        super(wsdlLocation, TILBAKEKREVINGSERVICE_QNAME);
    }

    public TilbakekrevingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TILBAKEKREVINGSERVICE_QNAME, features);
    }

    public TilbakekrevingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TilbakekrevingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TilbakekrevingPortType
     */
    @WebEndpoint(name = "TilbakekrevingServicePort")
    public TilbakekrevingPortType getTilbakekrevingServicePort() {
        return super.getPort(new QName("http://okonomi.nav.no/tilbakekrevingService/", "TilbakekrevingServicePort"), TilbakekrevingPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TilbakekrevingPortType
     */
    @WebEndpoint(name = "TilbakekrevingServicePort")
    public TilbakekrevingPortType getTilbakekrevingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://okonomi.nav.no/tilbakekrevingService/", "TilbakekrevingServicePort"), TilbakekrevingPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TILBAKEKREVINGSERVICE_EXCEPTION!= null) {
            throw TILBAKEKREVINGSERVICE_EXCEPTION;
        }
        return TILBAKEKREVINGSERVICE_WSDL_LOCATION;
    }

}
