//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.tilbakekreving.kravgrunnlag.detalj.v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="detaljertKravgrunnlag" type="{urn:no:nav:tilbakekreving:kravgrunnlag:detalj:v1}DetaljertKravgrunnlagDto"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "detaljertKravgrunnlag"
})
@XmlRootElement(name = "detaljertKravgrunnlagMelding")
public class DetaljertKravgrunnlagMelding {

    @XmlElement(required = true)
    protected DetaljertKravgrunnlagDto detaljertKravgrunnlag;

    /**
     * Gets the value of the detaljertKravgrunnlag property.
     * 
     * @return
     *     possible object is
     *     {@link DetaljertKravgrunnlagDto }
     *     
     */
    public DetaljertKravgrunnlagDto getDetaljertKravgrunnlag() {
        return detaljertKravgrunnlag;
    }

    /**
     * Sets the value of the detaljertKravgrunnlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetaljertKravgrunnlagDto }
     *     
     */
    public void setDetaljertKravgrunnlag(DetaljertKravgrunnlagDto value) {
        this.detaljertKravgrunnlag = value;
    }

}
