//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.16 at 09:21:04 PM CET 
//


package no.nav.tilbakekreving.typer.v1;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JaNeiDto.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JaNeiDto"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="J"/&gt;
 *     &lt;enumeration value="N"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "JaNeiDto")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
public enum JaNeiDto {

    J,
    N;

    public String value() {
        return name();
    }

    public static JaNeiDto fromValue(String v) {
        return valueOf(v);
    }

}
