//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.16 at 09:21:04 PM CET 
//


package no.nav.tilbakekreving.typer.v1;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * MMEL - Inneholder elementene som skal være med i en status output
 * 
 * <p>Java class for MmelDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MmelDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kodeMelding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="alvorlighetsgrad" type="{urn:no:nav:tilbakekreving:typer:v1}AlvorlighetsgradDto" minOccurs="0"/&gt;
 *         &lt;element name="beskrMelding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sqlKode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sqlState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sqlMelding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mqCompletionKode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mqReasonKode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="programId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sectionNavn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MmelDto", propOrder = {
    "systemId",
    "kodeMelding",
    "alvorlighetsgrad",
    "beskrMelding",
    "sqlKode",
    "sqlState",
    "sqlMelding",
    "mqCompletionKode",
    "mqReasonKode",
    "programId",
    "sectionNavn"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
public class MmelDto {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String systemId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String kodeMelding;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String alvorlighetsgrad;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String beskrMelding;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String sqlKode;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String sqlState;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String sqlMelding;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String mqCompletionKode;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String mqReasonKode;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String programId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    protected String sectionNavn;

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setSystemId(String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the kodeMelding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getKodeMelding() {
        return kodeMelding;
    }

    /**
     * Sets the value of the kodeMelding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setKodeMelding(String value) {
        this.kodeMelding = value;
    }

    /**
     * Gets the value of the alvorlighetsgrad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getAlvorlighetsgrad() {
        return alvorlighetsgrad;
    }

    /**
     * Sets the value of the alvorlighetsgrad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setAlvorlighetsgrad(String value) {
        this.alvorlighetsgrad = value;
    }

    /**
     * Gets the value of the beskrMelding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getBeskrMelding() {
        return beskrMelding;
    }

    /**
     * Sets the value of the beskrMelding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setBeskrMelding(String value) {
        this.beskrMelding = value;
    }

    /**
     * Gets the value of the sqlKode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getSqlKode() {
        return sqlKode;
    }

    /**
     * Sets the value of the sqlKode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setSqlKode(String value) {
        this.sqlKode = value;
    }

    /**
     * Gets the value of the sqlState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getSqlState() {
        return sqlState;
    }

    /**
     * Sets the value of the sqlState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setSqlState(String value) {
        this.sqlState = value;
    }

    /**
     * Gets the value of the sqlMelding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getSqlMelding() {
        return sqlMelding;
    }

    /**
     * Sets the value of the sqlMelding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setSqlMelding(String value) {
        this.sqlMelding = value;
    }

    /**
     * Gets the value of the mqCompletionKode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getMqCompletionKode() {
        return mqCompletionKode;
    }

    /**
     * Sets the value of the mqCompletionKode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setMqCompletionKode(String value) {
        this.mqCompletionKode = value;
    }

    /**
     * Gets the value of the mqReasonKode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getMqReasonKode() {
        return mqReasonKode;
    }

    /**
     * Sets the value of the mqReasonKode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setMqReasonKode(String value) {
        this.mqReasonKode = value;
    }

    /**
     * Gets the value of the programId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getProgramId() {
        return programId;
    }

    /**
     * Sets the value of the programId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setProgramId(String value) {
        this.programId = value;
    }

    /**
     * Gets the value of the sectionNavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public String getSectionNavn() {
        return sectionNavn;
    }

    /**
     * Sets the value of the sectionNavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-03-16T09:21:04+01:00", comments = "JAXB RI v2.3.0")
    public void setSectionNavn(String value) {
        this.sectionNavn = value;
    }

}
