//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.tilbakekreving.typer.v1;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.nav.tilbakekreving.typer.v1 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.nav.tilbakekreving.typer.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MmelDto }
     * 
     * @return
     *     the new instance of {@link MmelDto }
     */
    public MmelDto createMmelDto() {
        return new MmelDto();
    }

    /**
     * Create an instance of {@link PeriodeDto }
     * 
     * @return
     *     the new instance of {@link PeriodeDto }
     */
    public PeriodeDto createPeriodeDto() {
        return new PeriodeDto();
    }

}
