//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.16 at 09:21:01 PM CET 
//


package no.nav.virksomhet.tjenester.avstemming.meldinger.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="aksjon" type="{http://nav.no/virksomhet/tjenester/avstemming/meldinger/v1}Aksjonsdata"/&gt;
 *         &lt;element name="total" type="{http://nav.no/virksomhet/tjenester/avstemming/meldinger/v1}Totaldata" minOccurs="0"/&gt;
 *         &lt;element name="periode" type="{http://nav.no/virksomhet/tjenester/avstemming/meldinger/v1}Periodedata" minOccurs="0"/&gt;
 *         &lt;element name="grunnlag" type="{http://nav.no/virksomhet/tjenester/avstemming/meldinger/v1}Grunnlagsdata" minOccurs="0"/&gt;
 *         &lt;element name="detalj" type="{http://nav.no/virksomhet/tjenester/avstemming/meldinger/v1}Detaljdata" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aksjon",
    "total",
    "periode",
    "grunnlag",
    "detalj"
})
@XmlRootElement(name = "avstemmingsdata")
public class Avstemmingsdata {

    @XmlElement(required = true)
    protected Aksjonsdata aksjon;
    protected Totaldata total;
    protected Periodedata periode;
    protected Grunnlagsdata grunnlag;
    protected List<Detaljdata> detalj;

    /**
     * Gets the value of the aksjon property.
     * 
     * @return
     *     possible object is
     *     {@link Aksjonsdata }
     *     
     */
    public Aksjonsdata getAksjon() {
        return aksjon;
    }

    /**
     * Sets the value of the aksjon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aksjonsdata }
     *     
     */
    public void setAksjon(Aksjonsdata value) {
        this.aksjon = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Totaldata }
     *     
     */
    public Totaldata getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Totaldata }
     *     
     */
    public void setTotal(Totaldata value) {
        this.total = value;
    }

    /**
     * Gets the value of the periode property.
     * 
     * @return
     *     possible object is
     *     {@link Periodedata }
     *     
     */
    public Periodedata getPeriode() {
        return periode;
    }

    /**
     * Sets the value of the periode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periodedata }
     *     
     */
    public void setPeriode(Periodedata value) {
        this.periode = value;
    }

    /**
     * Gets the value of the grunnlag property.
     * 
     * @return
     *     possible object is
     *     {@link Grunnlagsdata }
     *     
     */
    public Grunnlagsdata getGrunnlag() {
        return grunnlag;
    }

    /**
     * Sets the value of the grunnlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grunnlagsdata }
     *     
     */
    public void setGrunnlag(Grunnlagsdata value) {
        this.grunnlag = value;
    }

    /**
     * Gets the value of the detalj property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detalj property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetalj().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Detaljdata }
     * 
     * 
     */
    public List<Detaljdata> getDetalj() {
        if (detalj == null) {
            detalj = new ArrayList<Detaljdata>();
        }
        return this.detalj;
    }

}
