//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.trygdeetaten.skjema.oppdrag;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Inneholder elementene som skal være med i en input 300-rekord, Simulering
 * 
 * <p>Java class for simulerings-periode-300 complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="simulerings-periode-300">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="datoSimulerFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/>
 *         <element name="datoSimulerTom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simulerings-periode-300", propOrder = {
    "datoSimulerFom",
    "datoSimulerTom"
})
public class SimuleringsPeriode300 {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoSimulerFom;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoSimulerTom;

    /**
     * Gets the value of the datoSimulerFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoSimulerFom() {
        return datoSimulerFom;
    }

    /**
     * Sets the value of the datoSimulerFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoSimulerFom(XMLGregorianCalendar value) {
        this.datoSimulerFom = value;
    }

    /**
     * Gets the value of the datoSimulerTom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoSimulerTom() {
        return datoSimulerTom;
    }

    /**
     * Sets the value of the datoSimulerTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoSimulerTom(XMLGregorianCalendar value) {
        this.datoSimulerTom = value;
    }

}
