//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 03:51:50 PM CET 
//


package no.trygdeetaten.skjema.oppdrag;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Inneholder alle output 301-rekord linjene, Simulering
 * 
 * <p>Java class for simulerings-resultat-301 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simulerings-resultat-301"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="simulerings-resultat-linje-301" type="{http://www.trygdeetaten.no/skjema/oppdrag}simulerings-resultat-linje-301" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="simuleringsResultat" type="{http://www.trygdeetaten.no/skjema/oppdrag}simuleringsResultat" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simulerings-resultat-301", propOrder = {
    "simuleringsResultatLinje301",
    "simuleringsResultat"
})
public class SimuleringsResultat301 {

    @XmlElement(name = "simulerings-resultat-linje-301")
    protected List<SimuleringsResultatLinje301> simuleringsResultatLinje301;
    protected List<SimuleringsResultat> simuleringsResultat;

    /**
     * Gets the value of the simuleringsResultatLinje301 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the simuleringsResultatLinje301 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimuleringsResultatLinje301().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimuleringsResultatLinje301 }
     * 
     * 
     */
    public List<SimuleringsResultatLinje301> getSimuleringsResultatLinje301() {
        if (simuleringsResultatLinje301 == null) {
            simuleringsResultatLinje301 = new ArrayList<SimuleringsResultatLinje301>();
        }
        return this.simuleringsResultatLinje301;
    }

    /**
     * Gets the value of the simuleringsResultat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the simuleringsResultat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimuleringsResultat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimuleringsResultat }
     * 
     * 
     */
    public List<SimuleringsResultat> getSimuleringsResultat() {
        if (simuleringsResultat == null) {
            simuleringsResultat = new ArrayList<SimuleringsResultat>();
        }
        return this.simuleringsResultat;
    }

}
