//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.trygdeetaten.skjema.oppdrag;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Typen beskriver formatet og begrensningene til fradragTillegg som kommer fra/til
 *                 Oppdrag.
 * 
 * <p>Java class for TfradragTillegg</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="TfradragTillegg">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="F"/>
 *     <enumeration value="T"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "TfradragTillegg")
@XmlEnum
public enum TfradragTillegg {

    F,
    T;

    public String value() {
        return name();
    }

    public static TfradragTillegg fromValue(String v) {
        return valueOf(v);
    }

}
