//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.16 at 09:20:59 PM CET 
//


package no.trygdeetaten.skjema.oppdrag;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TkodeStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TkodeStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NY"/&gt;
 *     &lt;enumeration value="LOPE"/&gt;
 *     &lt;enumeration value="HVIL"/&gt;
 *     &lt;enumeration value="SPER"/&gt;
 *     &lt;enumeration value="IKAT"/&gt;
 *     &lt;enumeration value="ATTE"/&gt;
 *     &lt;enumeration value="ANNU"/&gt;
 *     &lt;enumeration value="OPPH"/&gt;
 *     &lt;enumeration value="FBER"/&gt;
 *     &lt;enumeration value="REAK"/&gt;
 *     &lt;enumeration value="KORR"/&gt;
 *     &lt;enumeration value="FEIL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TkodeStatus")
@XmlEnum
public enum TkodeStatus {

    NY,
    LOPE,
    HVIL,
    SPER,
    IKAT,
    ATTE,
    ANNU,
    OPPH,
    FBER,
    REAK,
    KORR,
    FEIL;

    public String value() {
        return name();
    }

    public static TkodeStatus fromValue(String v) {
        return valueOf(v);
    }

}
