//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.trygdeetaten.skjema.oppdrag;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Inneholder elementene som skal være med i en input 190-rekord, Valuta
 * 
 * <p>Java class for valuta-190 complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="valuta-190">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="typeValuta">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="FAKT"/>
 *               <enumeration value="FRAM"/>
 *               <enumeration value="UTB"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="valuta">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="3"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="datoValutaFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato"/>
 *         <element name="feilreg" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tfeilreg" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "valuta-190", propOrder = {
    "typeValuta",
    "valuta",
    "datoValutaFom",
    "feilreg"
})
public class Valuta190 {

    @XmlElement(required = true)
    protected String typeValuta;
    @XmlElement(required = true)
    protected String valuta;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoValutaFom;
    protected String feilreg;

    /**
     * Gets the value of the typeValuta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeValuta() {
        return typeValuta;
    }

    /**
     * Sets the value of the typeValuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeValuta(String value) {
        this.typeValuta = value;
    }

    /**
     * Gets the value of the valuta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuta() {
        return valuta;
    }

    /**
     * Sets the value of the valuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuta(String value) {
        this.valuta = value;
    }

    /**
     * Gets the value of the datoValutaFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoValutaFom() {
        return datoValutaFom;
    }

    /**
     * Sets the value of the datoValutaFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoValutaFom(XMLGregorianCalendar value) {
        this.datoValutaFom = value;
    }

    /**
     * Gets the value of the feilreg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeilreg() {
        return feilreg;
    }

    /**
     * Sets the value of the feilreg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeilreg(String value) {
        this.feilreg = value;
    }

}
